intend fix

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -3,7 +3,7 @@ name: CareerCrush CD/CI
 on:
   push:
     branches:
-      - main  
+      - main
 
 jobs:
   build:
@@ -22,23 +22,26 @@ jobs:
       - name: Install dependencies
         run: npm install
       - name: Build
-        run: npm run build 
+        run: npm run build
+
+      # Check if build directory exists
       - name: Check if build directory exists
         run: |
-        if [ -d "build"]; then
-          exho "Build directory exists."
-          exist 0 # Exist with success code if dir exists
-        else 
-          echo " Build directory not found"
-          exit 1 #Exit with error code if dir does not exists
-        fi
-      continue-on-error: true
+          if [ -d "build" ]; then
+            echo "Build directory exists."
+            exit 0  # Exit with success code if directory exists
+          else
+            echo "Build directory not found."
+            exit 1  # Exit with error code if directory does not exist
+          fi
+        continue-on-error: true
 
-      #Upload to S3 if the "build" dir exists
+      # Upload to S3 if the "build" directory exists
       - name: Upload to S3
+        if: ${{ success() }}
         uses: shallwefootball/s3-upload-action@master
         with:
           aws_key_id: ${{ secrets.AWS_KEY_ID }}
           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws_bucket: ${{ secrets.AWS_BUCKET }}
-          source_dir: 'build'
+          source_dir: "build"
